'use strict';

(() => {
  const sessionUser = window.previEduCurrentUser;
  if (!sessionUser || sessionUser.role !== 'DIRECTOR') return;
  const db = window.supabaseClient;
  const menu = document.querySelector('#main-menu');
  const view = document.querySelector('#alerts-view');
  const alertLink = [...menu.querySelectorAll('.nav-link')].find((link) => link.textContent.trim() === 'Alertas');
  if (!view || !alertLink) return;

  const title = document.querySelector('#dashboard-title'); const subtitle = document.querySelector('#dashboard-subtitle'); const tabs = [...document.querySelectorAll('[data-alerts-tab]')];
  const analysisModal = new window.tabler.Modal(document.querySelector('#risk-analysis-modal')); const detailModal = new window.tabler.Modal(document.querySelector('#alert-detail-modal')); const followupModal = new window.tabler.Modal(document.querySelector('#follow-up-modal'));
  const state = { analyses: [], alerts: [], years: [], levels: [], grades: [], sections: [], classrooms: [], risks: [], alertStates: [], followupTypes: [], directorId: null, selectedAnalysis: null, selectedAlert: null, loaded: false, earlyPage: 1, closedPage: 1, pageSize: 10 };
  const relation = (item) => Array.isArray(item) ? item[0] : item;
  const value = (item, fallback = 'No registrado') => item === null || item === undefined || item === '' ? fallback : String(item);
  const normalize = (item) => value(item, '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
  const escapeHtml = (item) => value(item).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
  const fullName = (student) => [student?.nombres, student?.apellido_paterno, student?.apellido_materno].filter(Boolean).join(' ') || 'No registrado';
  const date = (item) => item ? new Intl.DateTimeFormat('es-PE', { timeZone: 'UTC' }).format(new Date(`${String(item).slice(0, 10)}T00:00:00Z`)) : 'No registrado';
  const data = (response, context) => { if (response.error) throw new Error(context, { cause: response.error }); return response.data; };
  const logError = (context, error) => console.error(`[Alertas] ${context}`, error.cause || error);
  const analysisParts = (analysis) => { const enrollment = relation(analysis?.matricula); const student = relation(enrollment?.estudiante); const classroom = relation(enrollment?.aula); const grade = relation(classroom?.grado); const level = relation(grade?.nivel_educativo); const section = relation(classroom?.seccion); const year = relation(classroom?.anio_escolar); const risk = relation(analysis?.nivel_riesgo); return { enrollment, student, classroom, grade, level, section, year, risk }; };
  const alertState = (alert) => relation(alert?.estado_alerta)?.codigo || 'SIN ALERTA';
  const riskPriority = { ALTO: 0, MEDIO: 1, BAJO: 2 };

  function feedback(message, success = true) { const element = document.querySelector('#alerts-feedback'); element.textContent = message; element.className = `alert students-feedback ${success ? 'alert-success' : 'alert-danger'}`; element.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }
  function riskBadge(code) { return `<span class="badge alert-risk risk-${normalize(code)}">${escapeHtml(code || 'Sin información')}</span>`; }
  function statusBadge(code) { return `<span class="badge alert-state state-${normalize(code)}">${escapeHtml(code || 'Sin alerta')}</span>`; }
  function setActiveMenu(active) { menu.querySelectorAll('.nav-link').forEach((link) => { link.classList.toggle('active', link === active); if (link === active) link.setAttribute('aria-current', 'page'); else link.removeAttribute('aria-current'); }); }
  function showAlerts(event) { event.preventDefault();['#dashboard-director', '#institution-view', '#academic-management-view', '#students-view', '#teachers-view'].forEach((selector) => document.querySelector(selector)?.classList.add('d-none')); view.classList.remove('d-none'); title.textContent = 'ALERTAS'; subtitle.textContent = 'Análisis preventivo y seguimiento de alertas tempranas'; setActiveMenu(alertLink); activateTab('analysis'); if (!state.loaded) initialize(); }
  function hideAlerts() { view.classList.add('d-none'); }
  function activateTab(name) { tabs.forEach((tab) => { const active = tab.dataset.alertsTab === name; tab.classList.toggle('active', active); tab.setAttribute('aria-selected', String(active)); }); document.querySelectorAll('.alerts-pane').forEach((pane) => pane.classList.toggle('d-none', pane.id !== `alerts-pane-${name}`)); }
  function fill(select, rows, placeholder, key, label) { select.replaceChildren(new Option(placeholder, '')); rows.forEach((row) => select.add(new Option(label(row), row[key]))); select.disabled = false; }

  /* Replaced below with the normalized loader.
  async function loadData() {
    const analysisSelect = 'analisis_riesgo_id,matricula_id,periodo_id,nivel_riesgo_id,fecha_analisis,descripcion,nivel_riesgo(nivel_riesgo_id,codigo,nombre),factor_analisis_riesgo(tipo_factor,descripcion,valor),matricula(matricula_id,estudiante(estudiante_id,codigo,nombres,apellido_paterno,apellido_materno),aula(aula_id,anio_escolar_id,grado_id,seccion_id,anio_escolar(anio_escolar_id,anio),grado(grado_id,nivel_id,nombre,nivel_educativo(nivel_id,nombre)),seccion(seccion_id,nombre))),alerta(alerta_id,estado_alerta_id,titulo,descripcion,fecha_generacion,fecha_cierre,fecha_actualizacion,estado_alerta(estado_alerta_id,codigo,nombre),seguimiento(seguimiento_id,fecha,descripcion,tipo_seguimiento(nombre),usuario(nombres,apellidos)))';
    const responses = await Promise.all([db.from('analisis_riesgo').select(analysisSelect).order('fecha_analisis', { ascending: false }), db.from('anio_escolar').select('anio_escolar_id,anio,estado').order('anio', { ascending: false }), db.from('nivel_educativo').select('nivel_id,nombre,estado').order('nombre'), db.from('grado').select('grado_id,nivel_id,nombre,orden,estado').order('orden'), db.from('seccion').select('seccion_id,nombre,estado').order('nombre'), db.from('aula').select('aula_id,anio_escolar_id,grado_id,seccion_id,estado'), db.from('nivel_riesgo').select('nivel_riesgo_id,codigo,nombre,estado').order('orden'), db.from('estado_alerta').select('estado_alerta_id,codigo,nombre,estado').order('orden'), db.from('tipo_seguimiento').select('tipo_seguimiento_id,codigo,nombre,estado').eq('estado', true).order('nombre'), db.from('usuario').select('usuario_id').eq('nombre_usuario', sessionUser.username).eq('rol', 'DIRECTOR').maybeSingle()]);
    state.analyses = data(responses[0], 'No se pudieron consultar los análisis.') || []; state.years = data(responses[1], 'No se pudieron consultar los años.') || []; state.levels = data(responses[2], 'No se pudieron consultar los niveles.') || []; state.grades = data(responses[3], 'No se pudieron consultar los grados.') || []; state.sections = data(responses[4], 'No se pudieron consultar las secciones.') || []; state.classrooms = data(responses Nederlanders, 'No se pudieron consultar las aulas.') || [];
    state.risks = data(responses[6], 'No se pudieron consultar los niveles de riesgo.') || []; state.alertStates = data(responses[7], 'No se pudieron consultar los estados de alerta.') || []; state.followupTypes = data(responses[8], 'No se pudieron consultar los tipos de seguimiento.') || []; state.directorId = data(responses[9], 'No se pudo resolver el usuario Director.')?.usuario_id || null;
    state.alerts = state.analyses.flatMap((analysis) => (analysis.alerta || []).map((alert) => ({ ...alert, analysis })));
  }

  */
  async function loadData() {
    const analysisSelect = 'analisis_riesgo_id,matricula_id,periodo_id,nivel_riesgo_id,fecha_analisis,descripcion,nivel_riesgo(nivel_riesgo_id,codigo,nombre),factor_analisis_riesgo(tipo_factor,descripcion,valor),matricula(matricula_id,estudiante(estudiante_id,codigo,nombres,apellido_paterno,apellido_materno),aula(aula_id,anio_escolar_id,grado_id,seccion_id,anio_escolar(anio_escolar_id,anio),grado(grado_id,nivel_id,nombre,nivel_educativo(nivel_id,nombre)),seccion(seccion_id,nombre))),alerta(alerta_id,estado_alerta_id,titulo,descripcion,fecha_generacion,fecha_cierre,fecha_actualizacion,estado_alerta(estado_alerta_id,codigo,nombre),seguimiento(seguimiento_id,fecha,descripcion,tipo_seguimiento(nombre),usuario(nombres,apellidos)))';
    const responses = await Promise.all([
      db.from('analisis_riesgo').select(analysisSelect).in('matricula_id', window.appContext.scope.enrollmentIds).order('fecha_analisis', { ascending: false }),
      db.from('anio_escolar').select('anio_escolar_id,anio,estado').eq('institucion_id', window.appContext.currentInstitution.institucion_id).order('anio', { ascending: false }),
      db.from('nivel_educativo').select('nivel_id,nombre,estado').order('nombre'),
      db.from('grado').select('grado_id,nivel_id,nombre,orden,estado').order('orden'),
      db.from('seccion').select('seccion_id,nombre,estado').order('nombre'),
      db.from('aula').select('aula_id,anio_escolar_id,grado_id,seccion_id,estado').in('anio_escolar_id', window.appContext.scope.yearIds),
      db.from('nivel_riesgo').select('nivel_riesgo_id,codigo,nombre,estado').order('orden'),
      db.from('estado_alerta').select('estado_alerta_id,codigo,nombre,estado').order('orden'),
      db.from('tipo_seguimiento').select('tipo_seguimiento_id,codigo,nombre,estado').eq('estado', true).order('nombre'),
      db.from('usuario').select('usuario_id').eq('nombre_usuario', sessionUser.username).eq('rol', 'DIRECTOR').maybeSingle()
    ]);
    state.analyses = data(responses[0], 'No se pudieron consultar los análisis.') || [];
    state.years = data(responses[1], 'No se pudieron consultar los años.') || [];
    state.levels = data(responses[2], 'No se pudieron consultar los niveles.') || [];
    state.grades = data(responses[3], 'No se pudieron consultar los grados.') || [];
    state.sections = data(responses[4], 'No se pudieron consultar las secciones.') || [];
    state.classrooms = data(responses[5], 'No se pudieron consultar las aulas.') || [];
    state.risks = data(responses[6], 'No se pudieron consultar los niveles de riesgo.') || [];
    state.alertStates = data(responses[7], 'No se pudieron consultar los estados de alerta.') || [];
    state.followupTypes = data(responses[8], 'No se pudieron consultar los tipos de seguimiento.') || [];
    state.directorId = data(responses[9], 'No se pudo resolver el usuario Director.')?.usuario_id || null;
    state.alerts = state.analyses.flatMap((analysis) => (analysis.alerta || []).map((alert) => ({ ...alert, analysis })));
  }

  function initializeFilters(container, alertMode = false) {
    fill(container.querySelector('[data-filter="year"]'), state.years, 'Todos', 'anio_escolar_id', (row) => row.anio); fill(container.querySelector('[data-filter="level"]'), state.levels, 'Todos', 'nivel_id', (row) => row.nombre); fill(container.querySelector('[data-filter="risk"]'), state.risks, 'Todos', 'codigo', (row) => row.nombre);
    if (alertMode) fill(container.querySelector('[data-filter="status"]'), state.alertStates.filter((row) => ['NUEVA', 'SEGUIMIENTO'].includes(row.codigo)), 'Todos', 'codigo', (row) => row.nombre);
    const rerender = () => alertMode ? renderEarlyAlerts() : renderAnalyses(); container.querySelectorAll('select,input').forEach((input) => input.addEventListener(input.tagName === 'INPUT' ? 'input' : 'change', rerender));
    container.querySelector('[data-filter="level"]').addEventListener('change', () => { const levelId = container.querySelector('[data-filter="level"]').value; const grade = container.querySelector('[data-filter="grade"]'); fill(grade, state.grades.filter((row) => !levelId || String(row.nivel_id) === levelId), 'Todos', 'grado_id', (row) => row.nombre); grade.disabled = !levelId; updateClassrooms(container); rerender(); });
    container.querySelector('[data-filter="grade"]').addEventListener('change', () => { updateClassrooms(container); rerender(); }); container.querySelector('[data-filter="year"]').addEventListener('change', () => { updateClassrooms(container); rerender(); });
  }
  function updateClassrooms(container) { const year = container.querySelector('[data-filter="year"]').value; const grade = container.querySelector('[data-filter="grade"]').value; const select = container.querySelector('[data-filter="classroom"]'); const rows = state.classrooms.filter((row) => (!year || String(row.anio_escolar_id) === year) && (!grade || String(row.grado_id) === grade)); fill(select, rows, 'Todas', 'aula_id', (row) => state.sections.find((section) => section.seccion_id === row.seccion_id)?.nombre || 'Aula'); select.disabled = !grade; }
  function matchesFilters(analysis, container) { const part = analysisParts(analysis); const get = (name) => container.querySelector(`[data-filter="${name}"]`)?.value || ''; const search = normalize(get('search')); return (!get('year') || String(part.year?.anio_escolar_id) === get('year')) && (!get('level') || String(part.level?.nivel_id) === get('level')) && (!get('grade') || String(part.grade?.grado_id) === get('grade')) && (!get('classroom') || String(part.classroom?.aula_id) === get('classroom')) && (!get('risk') || part.risk?.codigo === get('risk')) && (!search || normalize(`${part.student?.codigo} ${fullName(part.student)}`).includes(search)); }

  function renderIndicators() { const counts = { BAJO: 0, MEDIO: 0, ALTO: 0 }; state.analyses.forEach((item) => { const code = analysisParts(item).risk?.codigo; if (Object.hasOwn(counts, code)) counts[code] += 1; }); document.querySelector('#alerts-total-analysis').textContent = state.analyses.length; document.querySelector('#alerts-low-risk').textContent = counts.BAJO; document.querySelector('#alerts-medium-risk').textContent = counts.MEDIO; document.querySelector('#alerts-high-risk').textContent = counts.ALTO; document.querySelector('#alerts-active-count').textContent = state.alerts.filter((item) => ['NUEVA', 'SEGUIMIENTO'].includes(alertState(item))).length; }
  function renderAnalyses() { const rows = state.analyses.filter((item) => matchesFilters(item, document.querySelector('#analysis-filters'))).sort((a, b) => riskPriority[analysisParts(a).risk?.codigo] - riskPriority[analysisParts(b).risk?.codigo]); const body = document.querySelector('#risk-analysis-body'); body.replaceChildren(); rows.forEach((analysis) => { const part = analysisParts(analysis); const alert = analysis.alerta?.[0]; const row = document.createElement('tr'); row.innerHTML = `<td><strong>${escapeHtml(fullName(part.student))}</strong><small>${escapeHtml(part.student?.codigo)}</small></td><td>${escapeHtml(`${part.grade?.nombre || ''} ${part.section?.nombre || ''}`.trim())}</td><td>${riskBadge(part.risk?.codigo)}</td><td>${escapeHtml((analysis.factor_analisis_riesgo || []).slice(0, 2).map((factor) => factor.valor || factor.tipo_factor).join(' · '), 'Sin factores')}</td><td>${statusBadge(alertState(alert))}</td><td>${date(analysis.fecha_analisis)}</td>`; const action = document.createElement('td'); const button = document.createElement('button'); button.className = 'btn btn-sm btn-outline-primary'; button.textContent = 'Ver análisis'; button.addEventListener('click', () => openAnalysis(analysis)); action.appendChild(button); row.appendChild(action); body.appendChild(row); }); document.querySelector('#risk-analysis-table').classList.toggle('d-none', !rows.length); document.querySelector('#risk-analysis-empty').classList.toggle('d-none', rows.length > 0); }

  function filteredAlerts(closed) { const container = document.querySelector('#early-alert-filters'); let rows = state.alerts.filter((alert) => closed ? alertState(alert) === 'CERRADA' : ['NUEVA', 'SEGUIMIENTO'].includes(alertState(alert))); if (!closed) { rows = rows.filter((alert) => matchesFilters(alert.analysis, container) && (!container.querySelector('[data-filter="status"]').value || alertState(alert) === container.querySelector('[data-filter="status"]').value)); const order = container.querySelector('[data-filter="order"]').value; rows.sort((a, b) => order === 'old' ? String(a.fecha_generacion).localeCompare(String(b.fecha_generacion)) : order === 'risk' ? riskPriority[analysisParts(a.analysis).risk?.codigo] - riskPriority[analysisParts(b.analysis).risk?.codigo] : String(b.fecha_generacion).localeCompare(String(a.fecha_generacion))); } return rows; }
  function pagination(container, total, pageKey, render) { container.replaceChildren(); if (total <= state.pageSize) return; const pages = Math.ceil(total / state.pageSize); state[pageKey] = Math.min(state[pageKey], pages); const summary = document.createElement('span'); const start = (state[pageKey] - 1) * state.pageSize; summary.textContent = `Mostrando ${start + 1} a ${Math.min(start + state.pageSize, total)} de ${total} alertas`; const controls = document.createElement('div'); for (const [label, page] of [['«', 1], ['‹', state[pageKey] - 1], ['›', state[pageKey] + 1], ['»', pages]]) { const button = document.createElement('button'); button.type = 'button'; button.className = 'btn btn-sm btn-outline-secondary'; button.textContent = label; button.disabled = page < 1 || page > pages || page === state[pageKey]; button.addEventListener('click', () => { state[pageKey] = page; render(); }); controls.appendChild(button); } const size = document.createElement('select'); size.className = 'form-select form-select-sm';[10, 20, 30].forEach((number) => size.add(new Option(number, number, false, number === state.pageSize))); size.addEventListener('change', (event) => { state.pageSize = Number(event.target.value); state.earlyPage = 1; state.closedPage = 1; renderEarlyAlerts(); renderClosedAlerts(); }); controls.prepend(size); container.append(summary, controls); }
  function renderEarlyAlerts() { const rows = filteredAlerts(false); const start = (state.earlyPage - 1) * state.pageSize; const list = document.querySelector('#early-alert-list'); list.replaceChildren(); rows.slice(start, start + state.pageSize).forEach((alert) => { const part = analysisParts(alert.analysis); const card = document.createElement('article'); card.className = `early-alert-card risk-border-${normalize(part.risk?.codigo)}`; card.innerHTML = `<div class="early-alert-main"><div style=" width: 60%; "><h3>${escapeHtml(alert.titulo)}</h3><strong>${escapeHtml(fullName(part.student))}</strong><p>${escapeHtml(alert.descripcion)}</p><small>Presenta señales que requieren seguimiento. Se recomienda revisión preventiva.</small></div><div class="early-alert-meta">${statusBadge(alertState(alert))}<span>${date(alert.fecha_generacion)}</span></div></div>`; const actions = document.createElement('div'); actions.className = 'early-alert-actions'; const follow = document.createElement('button'); follow.className = 'btn btn-sm btn-primary'; follow.textContent = 'Registrar seguimiento'; follow.addEventListener('click', () => openFollowup(alert)); const detail = document.createElement('button'); detail.className = 'btn btn-sm btn-outline-primary'; detail.textContent = 'Detalle de alerta'; detail.addEventListener('click', () => openAlertDetail(alert)); actions.append(follow, detail); card.firstChild.appendChild(actions); list.appendChild(card); }); document.querySelector('#early-alert-empty').classList.toggle('d-none', rows.length > 0); pagination(document.querySelector('#early-alert-pagination'), rows.length, 'earlyPage', renderEarlyAlerts); }
  function renderClosedAlerts() { const rows = filteredAlerts(true); const start = (state.closedPage - 1) * state.pageSize; const body = document.querySelector('#closed-alerts-body'); body.replaceChildren(); rows.slice(start, start + state.pageSize).forEach((alert) => { const part = analysisParts(alert.analysis); const row = document.createElement('tr'); row.innerHTML = `<td>${escapeHtml(fullName(part.student))}</td><td>${escapeHtml(`${part.grade?.nombre || ''} ${part.section?.nombre || ''}`.trim())}</td><td>${riskBadge(part.risk?.codigo)}</td><td>${escapeHtml(alert.titulo)}</td><td>${date(alert.fecha_generacion)}</td><td>${date(alert.fecha_cierre)}</td>`; const action = document.createElement('td'); const button = document.createElement('button'); button.className = 'btn btn-sm btn-outline-primary'; button.textContent = 'Detalle de alerta'; button.addEventListener('click', () => openAlertDetail(alert)); action.appendChild(button); row.appendChild(action); body.appendChild(row); }); document.querySelector('#closed-alerts-table').classList.toggle('d-none', !rows.length); document.querySelector('#closed-alerts-empty').classList.toggle('d-none', rows.length > 0); pagination(document.querySelector('#closed-alert-pagination'), rows.length, 'closedPage', renderClosedAlerts); }

  function factorsHtml(analysis) { const factors = analysis.factor_analisis_riesgo || []; return factors.length ? `<div class="risk-factor-list">${factors.map((factor) => `<article><strong>${escapeHtml(value(factor.tipo_factor).replaceAll('_', ' '))}</strong><p>${escapeHtml(factor.descripcion)}</p><span>${escapeHtml(factor.valor)}</span></article>`).join('')}</div>` : '<p class="students-message">No hay factores registrados.</p>'; }
  function followupsHtml(alert) { const items = [...(alert?.seguimiento || [])].sort((a, b) => String(b.fecha).localeCompare(String(a.fecha))).slice(0, 3); return items.length ? `<div class="followup-list">${items.map((item) => `<article><strong>${date(item.fecha)} · ${escapeHtml(relation(item.tipo_seguimiento)?.nombre)}</strong><p>${escapeHtml(item.descripcion)}</p><small>${escapeHtml([relation(item.usuario)?.nombres, relation(item.usuario)?.apellidos].filter(Boolean).join(' '))}</small></article>`).join('')}</div><a href="#" class="attention-link">Ver todos los seguimientos</a>` : '<p class="students-message">Aún no tiene seguimientos registrados.</p>'; }
  async function openAnalysis(analysis) { state.selectedAnalysis = analysis; state.selectedAlert = analysis.alerta?.[0] || null; analysisModal.show(); const target = document.querySelector('#risk-analysis-detail'); const loading = document.querySelector('#risk-detail-loading'); target.innerHTML = ''; loading.classList.remove('d-none'); try { const part = analysisParts(analysis); const [attendanceResponse, gradesResponse] = await Promise.all([db.from('asistencia').select('fecha,estado_asistencia(codigo)').eq('matricula_id', analysis.matricula_id).order('fecha'), db.from('calificacion').select('calificacion_literal(codigo),periodo_evaluacion(periodo_id,nombre,orden)').eq('matricula_id', analysis.matricula_id)]); const attendance = data(attendanceResponse, 'No se pudo consultar la asistencia.') || []; const grades = data(gradesResponse, 'No se pudieron consultar las calificaciones.') || []; target.innerHTML = `<div class="profile-summary analysis-summary"><div><span>Estudiante</span><strong>${escapeHtml(fullName(part.student))}</strong></div><div><span>Código</span><strong>${escapeHtml(part.student?.codigo)}</strong></div><div><span>Nivel</span><strong>${escapeHtml(part.level?.nombre)}</strong></div><div><span>Grado / Sección</span><strong>${escapeHtml(`${part.grade?.nombre || ''} ${part.section?.nombre || ''}`.trim())}</strong></div><div><span>Nivel de riesgo</span>${riskBadge(part.risk?.codigo)}</div></div>${analysisAlertHtml(state.selectedAlert, part.year)}<section class="profile-card"><h3>Factores de riesgo identificados</h3>${factorsHtml(analysis)}</section><div class="profile-two-columns"><section class="profile-card"><h3>Resumen reciente de asistencia</h3>${attendanceHtml(attendance)}</section><section class="profile-card"><h3>Resumen académico</h3>${gradesHtml(grades)}</section></div><section class="profile-card"><h3>Últimos seguimientos</h3>${followupsHtml(state.selectedAlert)}</section>`; document.querySelector('#analysis-follow-up-button').classList.toggle('d-none', !state.selectedAlert || alertState(state.selectedAlert) === 'CERRADA'); } catch (error) { logError('Error al cargar análisis.', error); target.innerHTML = '<p class="students-message">No se pudo cargar la información.</p>'; } finally { loading.classList.add('d-none'); } }
  function analysisAlertHtml(alert, year) { return alert ? `<section class="profile-card alert-information"><h3>Información de la alerta</h3><div><span>Estado ${statusBadge(alertState(alert))}</span><span>Generación <strong>${date(alert.fecha_generacion)}</strong></span><span>Año escolar <strong>${escapeHtml(year?.anio)}</strong></span><span>Actualización <strong>${date(alert.fecha_actualizacion)}</strong></span></div></section>` : '<section class="profile-card"><p class="students-message">Este análisis no tiene alerta asociada.</p></section>'; }
  function attendanceHtml(rows) { if (!rows.length) return '<p class="students-message">Sin registros.</p>'; const months = new Map(); rows.forEach((row) => { const month = row.fecha.slice(0, 7); if (!months.has(month)) months.set(month, { A: 0, T: 0, FJ: 0, FNJ: 0, total: 0 }); const item = months.get(month); const code = relation(row.estado_asistencia)?.codigo; item.total += 1; if (Object.hasOwn(item, code)) item[code] += 1; }); const [month, last] = [...months].sort(([a], [b]) => b.localeCompare(a))[0]; return `<div class="attendance-recent"><strong>${((last.A / last.total) * 100).toFixed(1)}%</strong><span>${escapeHtml(month)} · último mes con registros</span></div><div class="literal-grid"><span>A <strong>${last.A}</strong></span><span>T <strong>${last.T}</strong></span><span>FJ <strong>${last.FJ}</strong></span><span>FNJ <strong>${last.FNJ}</strong></span></div>`; }
  function gradesHtml(rows) { if (!rows.length) return '<p class="students-message">No hay información disponible.</p>'; const periods = new Map(); rows.forEach((row) => { const period = relation(row.periodo_evaluacion); if (!period) return; if (!periods.has(period.periodo_id)) periods.set(period.periodo_id, { period, AD: 0, A: 0, B: 0, C: 0 }); const code = relation(row.calificacion_literal)?.codigo; if (['AD', 'A', 'B', 'C'].includes(code)) periods.get(period.periodo_id)[code] += 1; }); const latest = [...periods.values()].sort((a, b) => b.period.orden - a.period.orden)[0]; return latest ? `<p class="academic-period">${escapeHtml(latest.period.nombre)}</p><div class="literal-grid"><span>AD <strong>${latest.AD}</strong></span><span>A <strong>${latest.A}</strong></span><span>B <strong>${latest.B}</strong></span><span>C <strong>${latest.C}</strong></span></div>` : '<p class="students-message">No hay información disponible.</p>'; }

  function openAlertDetail(alert) { state.selectedAlert = alert; state.selectedAnalysis = alert.analysis; const part = analysisParts(alert.analysis); document.querySelector('#alert-detail-content').innerHTML = `<div class="profile-summary alert-detail-summary"><div><span>Estudiante</span><strong>${escapeHtml(fullName(part.student))}</strong></div><div><span>Código</span><strong>${escapeHtml(part.student?.codigo)}</strong></div><div><span>Nivel</span><strong>${escapeHtml(part.level?.nombre)}</strong></div><div><span>Grado / Sección</span><strong>${escapeHtml(`${part.grade?.nombre || ''} ${part.section?.nombre || ''}`.trim())}</strong></div><div><span>Riesgo</span>${riskBadge(part.risk?.codigo)}</div></div><section class="profile-card"><h3>${escapeHtml(alert.titulo)}</h3><p>${escapeHtml(alert.descripcion)}</p><div class="alert-dates"><span>Estado ${statusBadge(alertState(alert))}</span><span>Generación <strong>${date(alert.fecha_generacion)}</strong></span><span>Actualización <strong>${date(alert.fecha_actualizacion)}</strong></span></div></section><section class="profile-card"><h3>Factores relacionados</h3>${factorsHtml(alert.analysis)}</section>`; const closed = alertState(alert) === 'CERRADA'; document.querySelector('#detail-follow-up-button').classList.toggle('d-none', closed); document.querySelector('#close-alert-button').classList.toggle('d-none', closed); detailModal.show(); }
  function openFollowup(alert = state.selectedAlert) { if (!alert) return; state.selectedAlert = alert; const form = document.querySelector('#follow-up-form'); form.reset(); form.classList.remove('was-validated'); fill(form.elements.tipo_seguimiento_id, state.followupTypes, 'Seleccione un tipo', 'tipo_seguimiento_id', (item) => item.nombre); form.elements.fecha.value = new Date().toISOString().slice(0, 10); followupModal.show(); }
  async function saveFollowup(event) { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.classList.add('was-validated'); return; } if (!state.directorId || !state.selectedAlert) { feedback('No se pudo identificar el usuario responsable.', false); return; } const values = new FormData(form); const submit = form.querySelector('[type="submit"]'); submit.disabled = true; submit.textContent = 'Guardando seguimiento...'; try { data(await db.from('seguimiento').insert({ alerta_id: state.selectedAlert.alerta_id, usuario_id: state.directorId, tipo_seguimiento_id: Number(values.get('tipo_seguimiento_id')), fecha: values.get('fecha'), descripcion: values.get('descripcion').trim(), acuerdo: values.get('acuerdo').trim() || null, proxima_accion: values.get('proxima_accion').trim() || null, fecha_proxima_accion: values.get('fecha_proxima_accion') || null, fecha_registro: new Date().toISOString() }), 'No se pudo registrar el seguimiento.'); if (alertState(state.selectedAlert) === 'NUEVA') { const followState = state.alertStates.find((item) => item.codigo === 'SEGUIMIENTO'); data(await db.from('alerta').update({ estado_alerta_id: followState.estado_alerta_id, fecha_actualizacion: new Date().toISOString() }).eq('alerta_id', state.selectedAlert.alerta_id), 'No se pudo actualizar la alerta.'); } followupModal.hide(); feedback('Seguimiento registrado correctamente.'); await refresh(); } catch (error) { logError('Error al registrar seguimiento.', error); feedback('No se pudo guardar la información.', false); } finally { submit.disabled = false; submit.textContent = 'Guardar seguimiento'; } }
  async function closeAlert() { if (!state.selectedAlert || !window.confirm('¿Desea cerrar esta alerta?')) return; try { const closed = state.alertStates.find((item) => item.codigo === 'CERRADA'); const now = new Date().toISOString(); data(await db.from('alerta').update({ estado_alerta_id: closed.estado_alerta_id, fecha_cierre: now, fecha_actualizacion: now }).eq('alerta_id', state.selectedAlert.alerta_id), 'No se pudo cerrar la alerta.'); detailModal.hide(); feedback('Alerta cerrada correctamente.'); await refresh(); } catch (error) { logError('Error al cerrar alerta.', error); feedback('No se pudo guardar la información.', false); } }
  async function refresh() { await loadData(); renderIndicators(); renderAnalyses(); renderEarlyAlerts(); renderClosedAlerts(); }
  async function initialize() { try { await refresh(); initializeFilters(document.querySelector('#analysis-filters')); initializeFilters(document.querySelector('#early-alert-filters'), true); renderAnalyses(); renderEarlyAlerts(); state.loaded = true; } catch (error) { logError('Error al iniciar el módulo.', error); feedback('No se pudo cargar la información.', false); } finally { document.querySelector('#risk-analysis-loading').classList.add('d-none'); } }

  alertLink.addEventListener('click', showAlerts); document.querySelector('#dashboard-director .attention-link')?.addEventListener('click', showAlerts);[...menu.querySelectorAll('.nav-link')].filter((link) => link !== alertLink).forEach((link) => link.addEventListener('click', hideAlerts)); tabs.forEach((tab) => tab.addEventListener('click', () => activateTab(tab.dataset.alertsTab))); document.querySelector('#analysis-follow-up-button').addEventListener('click', () => openFollowup()); document.querySelector('#detail-follow-up-button').addEventListener('click', () => openFollowup()); document.querySelector('#detail-analysis-button').addEventListener('click', () => { detailModal.hide(); openAnalysis(state.selectedAnalysis); }); document.querySelector('#close-alert-button').addEventListener('click', closeAlert); document.querySelector('#follow-up-form').addEventListener('submit', saveFollowup);
})();
