'use strict';

(() => {
  if (window.appContext?.currentRole !== 'DOCENTE') return;
  const menu = document.querySelector('#main-menu');
  const main = document.querySelector('main .container-xl');
  const link = [...menu.querySelectorAll('.nav-link')].find((item) => item.textContent.trim() === 'Aulas');
  if (!link) return;
  main.insertAdjacentHTML('beforeend', `<section class="d-none teacher-classrooms" id="teacher-classrooms-view"><div class="alert d-none students-feedback" id="teacher-classrooms-feedback"></div><article class="card classrooms-filter-card"><div class="card-body classrooms-filters teacher-classroom-filters"><div><label class="form-label">Año escolar</label><select class="form-select" id="teacher-classrooms-year" disabled></select></div><div><label class="form-label">Nivel educativo</label><select class="form-select" id="teacher-classrooms-level"></select></div><div><label class="form-label">Buscar aula</label><input class="form-control" id="teacher-classrooms-search" type="search" placeholder="Grado o sección"></div><button class="btn btn-outline-secondary" id="teacher-classrooms-clear" type="button">Limpiar</button></div></article><div class="teacher-classroom-grid" id="teacher-classrooms-grid"></div><div class="teacher-empty d-none" id="teacher-classrooms-empty"><i class="ti ti-school-off"></i><strong>No tienes aulas asignadas en esta institución.</strong><p>Cuando el Director realice una asignación académica, aparecerá aquí.</p></div></section><div class="modal modal-blur fade" id="teacher-classroom-detail-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content classroom-detail"><div class="modal-header"><div><h2 class="modal-title" id="teacher-classroom-detail-title"></h2><p class="modal-subtitle" id="teacher-classroom-detail-subtitle"></p></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="teacher-classroom-detail-body"></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal">Cerrar</button></div></div></div></div>`);
  const $ = (selector) => document.querySelector(selector);
  const one = (value) => Array.isArray(value) ? value[0] : value;
  const esc = (value) => String(value ?? 'No registrado').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
  const normalize = (value) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
  const studentName = (student) => [student?.apellido_paterno, student?.apellido_materno, student?.nombres].filter(Boolean).join(' ') || 'No registrado';
  const roomName = (room) => `${room.grade?.nombre || ''} ${room.section?.nombre || ''}`.trim() || 'Aula';
  const tutorName = (room, teacherId) => { const teacher = one(room.tutoring?.docente); const person = one(teacher?.usuario); return { name: [person?.nombres, person?.apellidos].filter(Boolean).join(' ') || 'Sin tutor asignado', own: String(teacher?.docente_id || '') === String(teacherId || '') }; };
  const modal = new window.tabler.Modal($('#teacher-classroom-detail-modal'));
  let scope = null;

  function contextFor(room) { return { source: 'teacher-classrooms', anioEscolarId: room.classroom.anio_escolar_id, aulaId: room.classroom.aula_id, nivelId: room.level?.nivel_id, gradoId: room.classroom.grado_id, seccionId: room.classroom.seccion_id, areaCurricularId: room.areas.length === 1 ? room.areas[0].area_curricular_id : null }; }
  function go(target, room) { window.previEduNavigation?.set(target, contextFor(room)); modal.hide(); [...menu.querySelectorAll('.nav-link')].find((item) => item.textContent.trim() === (target === 'attendance' ? 'Asistencia' : 'Evaluaciones'))?.click(); }

  function filtered() { const level = $('#teacher-classrooms-level').value; const query = normalize($('#teacher-classrooms-search').value); return scope.classrooms.filter((room) => (!level || String(room.level?.nivel_id) === level) && (!query || normalize(`${roomName(room)} ${room.level?.nombre}`).includes(query))); }
  function render() { const rows = filtered(); $('#teacher-classrooms-grid').innerHTML = rows.map((room) => { const tutor = tutorName(room, scope.teacherId); return `<article class="card teacher-classroom-card"><div class="card-body"><div class="teacher-classroom-heading"><div><h2>${esc(roomName(room))}</h2><p>${esc(room.level?.nombre)} · ${esc(room.year?.anio)}</p></div><span class="badge teacher-status">Activo</span></div><dl><div><dt>Tutor</dt><dd>${esc(tutor.name)}${tutor.own ? ' <span class="badge bg-blue-lt">Tú</span>' : ''}</dd></div><div><dt>Estudiantes</dt><dd>${room.enrollments.length}</dd></div><div><dt>Mis áreas</dt><dd class="teacher-area-badges">${room.areas.map((area) => `<span>${esc(area.nombre)}</span>`).join('')}</dd></div></dl><div class="teacher-classroom-actions"><button class="btn btn-sm btn-outline-primary" data-detail="${room.classroom.aula_id}">Detalle</button><button class="btn btn-sm btn-outline-primary" data-go="attendance" data-room="${room.classroom.aula_id}">Asistencia</button><button class="btn btn-sm btn-primary" data-go="evaluations" data-room="${room.classroom.aula_id}">Evaluaciones</button></div></div></article>`; }).join(''); $('#teacher-classrooms-empty').classList.toggle('d-none', rows.length > 0); }
  function openDetail(room) { const tutor = tutorName(room, scope.teacherId); $('#teacher-classroom-detail-title').textContent = roomName(room); $('#teacher-classroom-detail-subtitle').textContent = `${room.level?.nombre || ''} · Año escolar ${room.year?.anio || ''}`; $('#teacher-classroom-detail-body').innerHTML = `<div class="classroom-detail-summary"><article><small>Tutor</small><strong>${esc(tutor.name)}${tutor.own ? ' · Tú' : ''}</strong></article><article><small>Estudiantes</small><strong>${room.enrollments.length}</strong></article><article><small>Mis áreas</small><strong>${esc(room.areas.map((area) => area.nombre).join(', '))}</strong></article></div><section class="profile-card"><h3>Estudiantes matriculados</h3>${room.enrollments.length ? `<div class="table-responsive"><table class="table table-vcenter classrooms-detail-table"><thead><tr><th>Código</th><th>Estudiante</th><th>Estado</th></tr></thead><tbody>${room.enrollments.map((enrollment) => { const student = one(enrollment.estudiante); return `<tr><td>${esc(student?.codigo)}</td><td>${esc(studentName(student))}</td><td><span class="badge teacher-status">Activo</span></td></tr>`; }).join('')}</tbody></table></div>` : '<p class="students-message">No hay estudiantes matriculados en esta aula.</p>'}</section><div class="classroom-quick-actions"><button class="btn btn-outline-primary" data-detail-go="attendance">Ir a Asistencia</button><button class="btn btn-primary" data-detail-go="evaluations">Ir a Evaluaciones</button></div>`; modal.show(); $('#teacher-classroom-detail-body').onclick = (event) => { const action = event.target.closest('[data-detail-go]'); if (action) go(action.dataset.detailGo, room); }; }
  async function load(force = false) { try { scope = await window.previEduTeacherScope.load(force); $('#teacher-classrooms-year').replaceChildren(new Option(scope.academicYear ? scope.academicYear.anio : 'Sin año escolar', scope.academicYear?.anio_escolar_id || '')); const levels = [...new Map(scope.classrooms.map((room) => [room.level?.nivel_id, room.level]).filter(([id]) => id)).values()]; $('#teacher-classrooms-level').replaceChildren(new Option('Todos los niveles', ''), ...levels.map((level) => new Option(level.nombre, level.nivel_id))); render(); const context = window.previEduNavigation?.consume('teacher-classrooms'); if (context?.aulaId) { const room = scope.classrooms.find((item) => item.classroom.aula_id === context.aulaId); if (room) openDetail(room); } } catch (error) { console.error('[Aulas Docente] No se pudo cargar:', error.cause || error); $('#teacher-classrooms-feedback').textContent = 'No se pudieron cargar tus aulas.'; $('#teacher-classrooms-feedback').className = 'alert students-feedback alert-danger'; } }
  function show(event) { event?.preventDefault(); document.querySelectorAll('main .container-xl > section').forEach((section) => section.classList.add('d-none')); $('#teacher-classrooms-view').classList.remove('d-none'); $('#dashboard-title').textContent = 'AULAS'; $('#dashboard-subtitle').textContent = 'Consulta tus aulas, estudiantes y áreas curriculares asignadas.'; menu.querySelectorAll('.nav-link').forEach((item) => item.classList.toggle('active', item === link)); load(); }
  link.onclick = show; $('#teacher-classrooms-level').onchange = render; $('#teacher-classrooms-search').oninput = render; $('#teacher-classrooms-clear').onclick = () => { $('#teacher-classrooms-level').value = ''; $('#teacher-classrooms-search').value = ''; render(); }; $('#teacher-classrooms-grid').onclick = (event) => { const detail = event.target.closest('[data-detail]'); const action = event.target.closest('[data-go]'); const id = Number(detail?.dataset.detail || action?.dataset.room); const room = scope?.classrooms.find((item) => item.classroom.aula_id === id); if (detail && room) openDetail(room); if (action && room) go(action.dataset.go, room); };
  window.addEventListener('previ:institution-change', () => { window.previEduTeacherScope.invalidate(); if (!$('#teacher-classrooms-view').classList.contains('d-none')) load(true); });
})();
