'use strict';
(() => {
  const user=window.previEduCurrentUser;if(!user||user.role!=='DIRECTOR')return;
  const db=window.supabaseClient,menu=document.querySelector('#main-menu'),main=document.querySelector('main .container-xl'),link=[...document.querySelectorAll('#main-menu .nav-link')].find(a=>a.textContent.trim()==='Evaluaciones');if(!db||!link)return;
  const sel=(n,l,d=false)=>`<div><label>${l}</label><select data-f="${n}"${d?' disabled':''}></select></div>`;
  main.insertAdjacentHTML('beforeend',`<section class="d-none compact-module" id="evaluations-view"><div class="alert d-none students-feedback" id="evaluations-feedback"></div><article class="card compact-query-card"><div class="card-body compact-filter-bar evaluation-query-bar" id="evaluations-filters">${sel('year','Año escolar')}${sel('level','Nivel')}${sel('grade','Grado',true)}${sel('room','Sección',true)}${sel('area','Área curricular',true)}${sel('period','Bimestre',true)}<button class="btn btn-primary" id="evaluations-query">Consultar</button></div></article><div class="compact-initial-state" id="evaluations-initial">Seleccione los filtros y presione Consultar.</div><div class="d-none" id="evaluations-results"><div class="compact-kpis" id="evaluations-kpis"></div><article class="card compact-results-card"><div class="card-header compact-results-header"><div><h2 class="card-title">Matriz de evaluación</h2><p id="evaluations-result-subtitle"></p></div><button class="btn btn-primary btn-sm" id="evaluations-save" disabled>Guardar cambios</button></div><div class="students-loading d-none" id="evaluations-loading"><span class="spinner-border spinner-border-sm"></span> Cargando información...</div><div class="evaluation-period-switcher d-none" id="evaluation-period-switcher"></div><div class="compact-matrix" id="evaluations-table-wrap"><table class="table table-vcenter compact-table evaluation-matrix" id="evaluations-table"><thead></thead><tbody></tbody></table></div><p class="students-message d-none" id="evaluations-empty"></p></article></div></section>`);
  const $=s=>document.querySelector(s),one=x=>Array.isArray(x)?x[0]:x,text=(x,f='')=>x===null||x===undefined?f:String(x),esc=x=>text(x,'No registrado').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]),name=s=>[s?.apellido_paterno,s?.apellido_materno,s?.nombres].filter(Boolean).join(' ')||'No registrado',data=(r,c)=>{if(r.error)throw new Error(c,{cause:r.error});return r.data||[];};
  const box=$('#evaluations-filters'),state={years:[],levels:[],grades:[],sections:[],rooms:[],roomAreas:[],areaLevels:[],areas:[],competencies:[],periods:[],literals:[],assignments:null,enrollments:[],gradesRows:[],selectedCompetencies:[],activePeriodId:null,pending:new Map(),loaded:false,queried:false};
  const get=n=>box.querySelector(`[data-f="${n}"]`),fill=(el,rows,p,key,label)=>{el.replaceChildren(new Option(p,''));rows.forEach(r=>el.add(new Option(label(r),r[key])));el.disabled=false;};
  async function catalogs(){const rs=await Promise.all([db.from('anio_escolar').select('anio_escolar_id,anio').eq('institucion_id',window.appContext.currentInstitution.institucion_id).order('anio',{ascending:false}),db.from('nivel_educativo').select('nivel_id,nombre'),db.from('grado').select('grado_id,nivel_id,nombre,orden').order('orden'),db.from('seccion').select('seccion_id,nombre'),db.from('aula').select('aula_id,anio_escolar_id,grado_id,seccion_id').in('anio_escolar_id',window.appContext.scope.yearIds),db.from('aula_area_curricular').select('aula_area_curricular_id,aula_id,area_curricular_nivel_id,estado').in('aula_id',window.appContext.scope.classroomIds),db.from('area_curricular_nivel').select('area_curricular_nivel_id,nivel_id,area_curricular_id,estado'),db.from('area_curricular').select('area_curricular_id,nombre,estado'),db.from('competencia').select('competencia_id,area_curricular_nivel_id,nombre,orden,estado').order('orden'),db.from('periodo_evaluacion').select('periodo_id,anio_escolar_id,nombre,orden,estado').in('anio_escolar_id',window.appContext.scope.yearIds).order('orden'),db.from('calificacion_literal').select('calificacion_literal_id,codigo,nombre').order('calificacion_literal_id')]);[state.years,state.levels,state.grades,state.sections,state.rooms,state.roomAreas,state.areaLevels,state.areas,state.competencies,state.periods,state.literals]=rs.map((r,i)=>data(r,`Catálogo ${i}`));fill(get('year'),state.years,'Seleccione','anio_escolar_id',r=>r.anio);fill(get('level'),state.levels,'Seleccione','nivel_id',r=>r.nombre);state.loaded=true;}
  function grades(){fill(get('grade'),state.grades.filter(r=>String(r.nivel_id)===get('level').value),'Seleccione','grado_id',r=>r.nombre);get('grade').disabled=!get('level').value;rooms();}
  function rooms(){const rows=state.rooms.filter(r=>String(r.anio_escolar_id)===get('year').value&&String(r.grado_id)===get('grade').value);fill(get('room'),rows,'Seleccione','aula_id',r=>state.sections.find(s=>s.seccion_id===r.seccion_id)?.nombre||'Aula');get('room').disabled=!(get('year').value&&get('grade').value);areas();}
  async function ensureAssignments(){if(state.assignments)return;state.assignments=data(await db.from('docente_aula_area').select('docente_aula_area_id,aula_area_curricular_id,estado,docente(docente_id,estado,usuario(nombres,apellidos))'),'Asignaciones docentes');}
  function classroomArea(areaId){const relation=state.areaLevels.find(r=>String(r.nivel_id)===get('level').value&&String(r.area_curricular_id)===String(areaId));return state.roomAreas.find(r=>r.estado&&String(r.aula_id)===get('room').value&&r.area_curricular_nivel_id===relation?.area_curricular_nivel_id);}
  function responsibleTeacher(areaId=get('area').value){const roomArea=classroomArea(areaId),assignment=state.assignments?.find(r=>r.estado&&r.aula_area_curricular_id===roomArea?.aula_area_curricular_id&&one(r.docente)?.estado==='ACTIVO'),person=one(one(assignment?.docente)?.usuario);return person?[person.nombres,person.apellidos].filter(Boolean).join(' '):'Docente no asignado';}
  async function areas(){const relations=state.roomAreas.filter(r=>r.estado&&String(r.aula_id)===get('room').value).map(r=>state.areaLevels.find(x=>x.area_curricular_nivel_id===r.area_curricular_nivel_id)).filter(Boolean),rows=relations.map(r=>state.areas.find(a=>a.area_curricular_id===r.area_curricular_id)).filter(Boolean);try{await ensureAssignments();}catch(error){console.error('[Evaluaciones] No se pudo resolver docentes',error.cause||error);}fill(get('area'),rows,'Seleccione','area_curricular_id',r=>`${r.nombre} — ${responsibleTeacher(r.area_curricular_id)}`);get('area').disabled=!get('room').value;periods();}
  function periods(){const rows=state.periods.filter(r=>String(r.anio_escolar_id)===get('year').value);fill(get('period'),rows,'Todos los bimestres','periodo_id',r=>r.nombre);get('period').options[0].value='all';get('period').disabled=!get('year').value;}
  function relationId(){return state.areaLevels.find(r=>String(r.nivel_id)===get('level').value&&String(r.area_curricular_id)===get('area').value)?.area_curricular_nivel_id;}function confirmDiscard(){if(!state.pending.size)return true;if(!confirm('Tiene cambios sin guardar. ¿Desea continuar y descartarlos?'))return false;state.pending.clear();$('#evaluations-save').disabled=true;return true;}function stale(){if(!confirmDiscard())return false;if(state.queried){state.queried=false;$('#evaluations-results').classList.add('d-none');$('#evaluations-initial').textContent='Los filtros cambiaron. Presione Consultar para actualizar los resultados.';$('#evaluations-initial').classList.remove('d-none');}return true;}
  async function query(){
    if(!confirmDiscard())return;
    if(!['year','level','grade','room','area','period'].every(n=>get(n).value)){feedback('Seleccione todos los filtros antes de consultar.',false);return;}
    const button=$('#evaluations-query');button.disabled=true;button.textContent='Consultando...';$('#evaluations-loading').classList.remove('d-none');
    try{
      state.enrollments=data(await db.from('matricula').select('matricula_id,estudiante(estudiante_id,codigo,nombres,apellido_paterno,apellido_materno)').eq('aula_id',+get('room').value).eq('estado',true),'Matrículas').sort((a,b)=>name(one(a.estudiante)).localeCompare(name(one(b.estudiante))));
      state.selectedCompetencies=state.competencies.filter(c=>c.estado&&c.area_curricular_nivel_id===relationId()).sort((a,b)=>a.orden-b.orden);
      const ids=state.enrollments.map(m=>m.matricula_id),competenceIds=state.selectedCompetencies.map(c=>c.competencia_id),yearPeriods=state.periods.filter(p=>String(p.anio_escolar_id)===get('year').value),selectedPeriod=get('period').value;
      state.activePeriodId=selectedPeriod==='all'?yearPeriods[0]?.periodo_id:+selectedPeriod;
      if(ids.length&&competenceIds.length){let request=db.from('calificacion').select('calificacion_id,matricula_id,periodo_id,competencia_id,calificacion_literal_id,observacion,calificacion_literal(codigo)').in('matricula_id',ids).in('competencia_id',competenceIds);request=selectedPeriod==='all'?request.in('periodo_id',yearPeriods.map(p=>p.periodo_id)):request.eq('periodo_id',+selectedPeriod);state.gradesRows=data(await request,'Calificaciones');}else state.gradesRows=[];
      state.pending.clear();state.queried=true;render();feedback('');
    }catch(error){console.error('[Evaluaciones]',error.cause||error);feedback('No se pudo cargar la información.',false);}
    finally{button.disabled=false;button.textContent='Consultar';$('#evaluations-loading').classList.add('d-none');}
  }
  const record=(m,c,p=state.activePeriodId)=>state.gradesRows.find(r=>r.matricula_id===m&&r.competencia_id===c&&r.periodo_id===p),options=selected=>`<option value="">Sin calificación</option>${state.literals.filter(l=>['AD','A','B','C'].includes(l.codigo)).map(l=>`<option value="${l.codigo}"${l.codigo===selected?' selected':''}>${l.codigo}</option>`).join('')}`;
  function change(matriculaId,competenciaId,code,el){const old=record(matriculaId,competenciaId),periodoId=state.activePeriodId;if(old&&!code){el.value=one(old.calificacion_literal)?.codigo||'';applyLiteralColor(el);feedback('Una calificación existente debe reemplazarse por AD, A, B o C.',false);return;}state.pending.set(`${matriculaId}|${periodoId}|${competenciaId}`,{old,matricula_id:matriculaId,periodo_id:periodoId,competencia_id:competenciaId,codigo:code});el.closest('td').classList.add('pending-cell');applyLiteralColor(el);$('#evaluations-save').disabled=false;renderKpis();}
  function render(){const table=$('#evaluations-table');$('#evaluations-results').classList.remove('d-none');$('#evaluations-initial').classList.add('d-none');if(!state.enrollments.length){empty('No existen estudiantes matriculados para el aula seleccionada.');return;}if(!state.selectedCompetencies.length){empty('No existen competencias registradas para el área seleccionada.');return;}$('#evaluations-empty').classList.add('d-none');$('#evaluations-table-wrap').classList.remove('d-none');$('#evaluations-result-subtitle').textContent=`${get('area').selectedOptions[0].textContent} · ${get('period').selectedOptions[0].textContent}`;table.tHead.innerHTML=`<tr><th class="student-sticky">Estudiante</th>${state.selectedCompetencies.map(c=>`<th title="${esc(c.nombre)}">${esc(c.nombre)}</th>`).join('')}</tr>`;table.tBodies[0].innerHTML=state.enrollments.map(m=>{const s=one(m.estudiante);return`<tr><td class="student-sticky"><strong>${esc(name(s))}</strong><small>${esc(s?.codigo)}</small></td>${state.selectedCompetencies.map(c=>{const r=record(m.matricula_id,c.competencia_id);return`<td><select class="matrix-select literal-select" data-matricula="${m.matricula_id}" data-competencia="${c.competencia_id}">${options(one(r?.calificacion_literal)?.codigo||'')}</select></td>`;}).join('')}</tr>`;}).join('');document.querySelectorAll('.literal-select').forEach(el=>el.onchange=()=>change(+el.dataset.matricula,+el.dataset.competencia,el.value,el));renderKpis();if(!state.gradesRows.length)feedback('No existen evaluaciones registradas. Puede ingresar las calificaciones en la matriz.');}
  function applyLiteralColor(select){select.classList.remove('grade-ad','grade-a','grade-b','grade-c','grade-empty');select.classList.add(select.value?`grade-${select.value.toLowerCase()}`:'grade-empty');}
  function renderPeriodSwitcher(){const switcher=$('#evaluation-period-switcher'),all=get('period').value==='all',periodRows=state.periods.filter(p=>String(p.anio_escolar_id)===get('year').value);switcher.classList.toggle('d-none',!all);switcher.replaceChildren();if(!all)return;periodRows.forEach(period=>{const button=document.createElement('button');button.type='button';button.className=`btn btn-sm ${period.periodo_id===state.activePeriodId?'btn-primary':'btn-outline-secondary'}`;button.textContent=period.nombre;button.onclick=()=>{state.activePeriodId=period.periodo_id;render();};switcher.append(button);});}
  const renderMatrix=render;render=()=>{renderMatrix();if(!state.enrollments.length||!state.selectedCompetencies.length)return;document.querySelectorAll('.literal-select').forEach(select=>{const key=`${select.dataset.matricula}|${state.activePeriodId}|${select.dataset.competencia}`,pending=state.pending.get(key);if(pending)select.value=pending.codigo;applyLiteralColor(select);});renderPeriodSwitcher();renderKpis();const area=state.areas.find(r=>String(r.area_curricular_id)===get('area').value),grade=state.grades.find(r=>String(r.grado_id)===get('grade').value),room=state.rooms.find(r=>String(r.aula_id)===get('room').value),section=state.sections.find(r=>r.seccion_id===room?.seccion_id);$('#evaluations-result-subtitle').innerHTML=`<span><b>Área curricular:</b> ${esc(area?.nombre)}</span><span><b>Docente:</b> ${esc(responsibleTeacher())}</span><span><b>Aula:</b> ${esc(`${grade?.nombre||''} ${section?.nombre||''}`.trim())}</span><span><b>Periodo:</b> ${esc(get('period').selectedOptions[0]?.textContent)}</span>`;};
  function currentCodes(){const codes=[];state.enrollments.forEach(m=>state.selectedCompetencies.forEach(c=>{const key=`${m.matricula_id}|${state.activePeriodId}|${c.competencia_id}`,pending=state.pending.get(key),old=record(m.matricula_id,c.competencia_id),code=pending?.codigo||one(old?.calificacion_literal)?.codigo;if(code)codes.push(code);}));return codes;}function renderKpis(){const codes=currentCodes(),counts={AD:0,A:0,B:0,C:0};codes.forEach(c=>counts[c]++);const items=[['Estudiantes',state.enrollments.length],['Competencias',state.selectedCompetencies.length],['AD',counts.AD],['A',counts.A],['B',counts.B],['C',counts.C]];$('#evaluations-kpis').innerHTML=items.map((x,index)=>`<div class="evaluation-kpi evaluation-kpi-${index<2?'neutral':x[0].toLowerCase()}"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');}function empty(msg){$('#evaluations-table-wrap').classList.add('d-none');$('#evaluations-empty').textContent=msg;$('#evaluations-empty').classList.remove('d-none');$('#evaluations-kpis').innerHTML='';$('#evaluation-period-switcher').classList.add('d-none');}
  async function save(){const changes=[...state.pending.values()].filter(x=>x.codigo);if(!changes.length)return;const button=$('#evaluations-save');button.disabled=true;button.textContent='Guardando cambios...';try{const responses=await Promise.all(changes.map(x=>{const literal=state.literals.find(l=>l.codigo===x.codigo),payload={matricula_id:x.matricula_id,periodo_id:x.periodo_id,competencia_id:x.competencia_id,calificacion_literal_id:literal.calificacion_literal_id,fecha_actualizacion:new Date().toISOString()};return x.old?db.from('calificacion').update(payload).eq('calificacion_id',x.old.calificacion_id):db.from('calificacion').insert({...payload,fecha_registro:new Date().toISOString()});}));if(responses.some(r=>r.error))throw new Error('SAVE',{cause:responses.find(r=>r.error)?.error});state.pending.clear();feedback('Cambios guardados correctamente.');await query();}catch(error){console.error('[Evaluaciones]',error.cause||error);feedback('No fue posible guardar todos los cambios.',false);}finally{button.textContent='Guardar cambios';button.disabled=!state.pending.size;}}
  function feedback(msg,good=true){const el=$('#evaluations-feedback');if(!msg){el.classList.add('d-none');return;}el.textContent=msg;el.className=`alert students-feedback ${good?'alert-success':'alert-danger'}`;}function show(e){e.preventDefault();['#dashboard-director','#institution-view','#academic-management-view','#students-view','#teachers-view','#attendance-view','#alerts-view','#followups-view','#reports-view'].forEach(s=>$(s)?.classList.add('d-none'));$('#evaluations-view').classList.remove('d-none');$('#dashboard-title').textContent='EVALUACIONES';$('#dashboard-subtitle').textContent='Consulte y gestione las evaluaciones registradas de los estudiantes.';menu.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a===link));if(!state.loaded)catalogs().catch(e=>{console.error('[Evaluaciones]',e.cause||e);feedback('No se pudo cargar la información.',false);});}
  get('level').onchange=()=>{if(stale())grades();};get('year').onchange=()=>{if(stale()){rooms();periods();}};get('grade').onchange=()=>{if(stale())rooms();};get('room').onchange=()=>{if(stale())areas();};['area','period'].forEach(n=>get(n).onchange=stale);menu.addEventListener('click',e=>{const target=e.target.closest('.nav-link');if(target&&target!==link&&!$('#evaluations-view').classList.contains('d-none')&&!confirmDiscard()){e.preventDefault();e.stopImmediatePropagation();}},true);link.onclick=show;[...menu.querySelectorAll('.nav-link')].filter(a=>a!==link).forEach(a=>a.addEventListener('click',()=>$('#evaluations-view').classList.add('d-none')));$('#evaluations-query').onclick=query;$('#evaluations-save').onclick=save;
})();
