'use strict';

(() => {
  if (window.appContext?.currentRole !== 'ADMINISTRADOR') return;
  const db = window.supabaseClient;
  const main = document.querySelector('main .container-xl');
  const menu = document.querySelector('#main-menu');
  const link = [...menu.querySelectorAll('.nav-link')].find((item) => item.textContent.trim() === 'Instituciones');
  if (!db || !main || !link) return;

  main.insertAdjacentHTML('beforeend', `
    <section class="d-none" id="admin-institutions" aria-label="Gestión de instituciones">
      <div class="card admin-panel"><div class="card-header admin-section-header"><div><h2 class="card-title">Instituciones</h2><p class="text-secondary mb-0">Administre las instituciones educativas registradas en PREVI-EDU.</p></div><button class="btn btn-primary" id="new-admin-institution" type="button"><i class="ti ti-plus"></i> Nueva institución</button></div>
        <div class="card-body admin-filters"><div><label class="form-label">Buscar</label><input class="form-control" id="admin-institution-search" type="search" placeholder="Código modular o nombre"></div><div><label class="form-label">Estado</label><select class="form-select" id="admin-institution-status"><option value="">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></div><button class="btn btn-outline-secondary" id="clear-admin-institution-filters" type="button">Limpiar</button></div>
        <div class="alert d-none mx-3 mt-3 mb-0" id="admin-institution-feedback" role="status"></div><div class="admin-loading" id="admin-institutions-loading"><span class="spinner-border spinner-border-sm"></span> Cargando instituciones...</div><div class="table-responsive d-none" id="admin-institutions-table"><table class="table table-vcenter card-table"><thead><tr><th>Código modular</th><th>Institución</th><th>Ubicación</th><th>Gestión</th><th>UGEL</th><th>Estado</th><th>Acciones</th></tr></thead><tbody></tbody></table></div><div class="admin-empty d-none" id="admin-institutions-empty"><i class="ti ti-building-off"></i><strong>No hay instituciones registradas.</strong><span>Registre la primera institución para comenzar.</span><button class="btn btn-primary btn-sm" type="button" data-empty-new>Nueva institución</button></div><div class="admin-pagination" id="admin-institutions-pagination"></div>
      </div>
    </section>
    <div class="modal modal-blur fade" id="admin-institution-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><form class="modal-content" id="admin-institution-form" novalidate><div class="modal-header"><div><h2 class="modal-title">Nueva institución</h2><p class="modal-subtitle">Información general de la institución educativa</p></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><div class="alert alert-danger d-none" data-form-error role="alert"></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Código modular *</label><input class="form-control" name="codigo_modular" required></div><div class="col-md-6"><label class="form-label">Nombre *</label><input class="form-control" name="nombre" required></div><div class="col-md-6"><label class="form-label">Gestión *</label><select class="form-select" name="gestion" required></select></div><div class="col-md-3"><label class="form-label">DRE</label><input class="form-control" name="dre"></div><div class="col-md-3"><label class="form-label">UGEL</label><input class="form-control" name="ugel"></div><div class="col-md-4"><label class="form-label">Departamento *</label><input class="form-control" name="departamento" required></div><div class="col-md-4"><label class="form-label">Provincia *</label><input class="form-control" name="provincia" required></div><div class="col-md-4"><label class="form-label">Distrito *</label><input class="form-control" name="distrito" required></div><div class="col-12"><label class="form-label">Dirección</label><input class="form-control" name="direccion"></div><div class="col-12"><label class="form-check form-switch"><input class="form-check-input" name="estado" type="checkbox" checked><span class="form-check-label">Institución activa</span></label></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Guardar institución</button></div></form></div></div>`);

  const view = document.querySelector('#admin-institutions'); const form = document.querySelector('#admin-institution-form'); const modal = new window.tabler.Modal(document.querySelector('#admin-institution-modal'));
  const state = { rows: [], filtered: [], editing: null, page: 1, size: 10 };
  const safe = (value, fallback = 'No registrado') => value === null || value === undefined || value === '' ? fallback : String(value);
  const esc = (value) => safe(value).replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
  const normalize = (value) => safe(value, '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
  const active = (value) => value === true || String(value).toUpperCase() === 'ACTIVO';
  const check = (response, label) => { if (response.error) throw new Error(label, { cause: response.error }); return response.data || []; };
  function feedback(message, success = true) { const box = document.querySelector('#admin-institution-feedback'); box.textContent = message; box.className = `alert mx-3 mt-3 mb-0 ${success ? 'alert-success' : 'alert-danger'}`; }
  function show() { document.querySelectorAll('#admin-dashboard,#admin-directors,#admin-users').forEach((item) => item?.classList.add('d-none')); view.classList.remove('d-none'); document.querySelector('#dashboard-title').textContent = 'Instituciones'; document.querySelector('#dashboard-subtitle').textContent = 'Administre las instituciones educativas registradas en PREVI-EDU.'; menu.querySelectorAll('.nav-link').forEach((item) => { item.classList.toggle('active', item === link); item.toggleAttribute('aria-current', item === link); }); load(); }
  async function load() { const loading=document.querySelector('#admin-institutions-loading'); loading.classList.remove('d-none'); try { state.rows=check(await db.from('institucion_educativa').select('institucion_id,codigo_modular,nombre,gestion,dre,ugel,departamento,provincia,distrito,direccion,estado').order('nombre'),'Instituciones'); applyFilters(); } catch(error){console.error('[Instituciones] Error al consultar:',error.cause||error); feedback('No se pudo cargar la información.',false);} finally{loading.classList.add('d-none');} }
  function applyFilters(){const query=normalize(document.querySelector('#admin-institution-search').value),status=document.querySelector('#admin-institution-status').value;state.filtered=state.rows.filter((row)=>(!query||normalize(`${row.codigo_modular} ${row.nombre}`).includes(query))&&(!status||(status==='active')===active(row.estado)));state.page=1;render();}
  function render(){const total=state.filtered.length,start=(state.page-1)*state.size,rows=state.filtered.slice(start,start+state.size),table=document.querySelector('#admin-institutions-table'),empty=document.querySelector('#admin-institutions-empty');table.querySelector('tbody').innerHTML=rows.map((row)=>`<tr><td>${esc(row.codigo_modular)}</td><td><strong>${esc(row.nombre)}</strong><small class="d-block text-secondary">${esc(row.departamento)}</small></td><td>${esc([row.distrito,row.provincia].filter(Boolean).join(', '))}</td><td>${esc(row.gestion)}</td><td>${esc(row.ugel)}</td><td><span class="badge admin-status ${active(row.estado)?'is-active':'is-inactive'}">${active(row.estado)?'Activo':'Inactivo'}</span></td><td><div class="admin-row-actions"><button class="btn btn-sm btn-outline-primary" data-edit="${row.institucion_id}" type="button">Editar</button><button class="btn btn-sm btn-outline-secondary" data-toggle="${row.institucion_id}" type="button">${active(row.estado)?'Inactivar':'Activar'}</button></div></td></tr>`).join('');table.classList.toggle('d-none',!total);empty.classList.toggle('d-none',Boolean(total));renderPagination(total);}
  function renderPagination(total){const pages=Math.max(1,Math.ceil(total/state.size)),box=document.querySelector('#admin-institutions-pagination'),from=total?(state.page-1)*state.size+1:0,to=Math.min(state.page*state.size,total);box.innerHTML=`<span>Mostrando ${from} a ${to} de ${total} instituciones</span><div><select class="form-select form-select-sm" aria-label="Registros por página">${[10,20,30].map((size)=>`<option ${size===state.size?'selected':''}>${size}</option>`).join('')}</select><button class="btn btn-sm btn-outline-secondary" ${state.page===1?'disabled':''} data-page="prev">‹</button><span>${state.page} / ${pages}</span><button class="btn btn-sm btn-outline-secondary" ${state.page>=pages?'disabled':''} data-page="next">›</button></div>`;box.querySelector('select').onchange=(event)=>{state.size=Number(event.target.value);state.page=1;render();};box.querySelectorAll('[data-page]').forEach((button)=>button.onclick=()=>{state.page+=button.dataset.page==='next'?1:-1;render();});}
  function openForm(row=null){state.editing=row;form.reset();form.classList.remove('was-validated');form.querySelector('[data-form-error]').classList.add('d-none');form.querySelector('.modal-title').textContent=row?'Editar institución':'Nueva institución';const values=[...new Set(state.rows.map((item)=>item.gestion).filter(Boolean))].sort();const management=form.elements.gestion;management.replaceChildren(new Option('Seleccione la gestión',''));values.forEach((value)=>management.add(new Option(value,value)));if(row&&!values.includes(row.gestion))management.add(new Option(row.gestion,row.gestion));['codigo_modular','nombre','gestion','dre','ugel','departamento','provincia','distrito','direccion'].forEach((name)=>form.elements[name].value=row?.[name]??'');form.elements.estado.checked=row?active(row.estado):true;modal.show();}
  async function save(event){event.preventDefault();form.classList.add('was-validated');if(!form.checkValidity())return;const payload={};['codigo_modular','nombre','gestion','dre','ugel','departamento','provincia','distrito','direccion'].forEach((name)=>payload[name]=form.elements[name].value.trim()||null);payload.estado=form.elements.estado.checked;const errorBox=form.querySelector('[data-form-error]'),button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent='Guardando...';try{let duplicate=db.from('institucion_educativa').select('institucion_id').ilike('codigo_modular',payload.codigo_modular);if(state.editing)duplicate=duplicate.neq('institucion_id',state.editing.institucion_id);const existing=check(await duplicate,'Validación de código');if(existing.length){errorBox.textContent='Ya existe una institución con este código modular.';errorBox.classList.remove('d-none');return;}const response=state.editing?await db.from('institucion_educativa').update(payload).eq('institucion_id',state.editing.institucion_id):await db.from('institucion_educativa').insert(payload);check(response,'Guardar institución');modal.hide();feedback(state.editing?'Información actualizada correctamente.':'Institución registrada correctamente.');await load();window.dispatchEvent(new Event('previ:institutions-updated'));}catch(error){console.error('[Instituciones] Error al guardar:',error.cause||error);errorBox.textContent='No se pudo guardar la información.';errorBox.classList.remove('d-none');}finally{button.disabled=false;button.textContent='Guardar institución';}}
  async function toggle(row){const next=!active(row.estado);if(!next&&!window.confirm('¿Desea inactivar esta institución?\n\nLa institución dejará de estar disponible para nuevas operaciones mientras permanezca inactiva.'))return;try{check(await db.from('institucion_educativa').update({estado:next}).eq('institucion_id',row.institucion_id),'Actualizar estado');feedback(`Institución ${next?'activada':'inactivada'} correctamente.`);await load();window.dispatchEvent(new Event('previ:institutions-updated'));}catch(error){console.error('[Instituciones] Error al actualizar estado:',error.cause||error);feedback('No se pudo actualizar la información.',false);}}
  link.addEventListener('click',(event)=>{event.preventDefault();show();});document.querySelector('#new-admin-institution').onclick=()=>openForm();view.querySelector('[data-empty-new]').onclick=()=>openForm();document.querySelector('#admin-institution-search').addEventListener('input',applyFilters);document.querySelector('#admin-institution-status').addEventListener('change',applyFilters);document.querySelector('#clear-admin-institution-filters').onclick=()=>{document.querySelector('#admin-institution-search').value='';document.querySelector('#admin-institution-status').value='';applyFilters();};document.querySelector('#admin-institutions-table tbody').addEventListener('click',(event)=>{const edit=event.target.closest('[data-edit]'),change=event.target.closest('[data-toggle]'),id=edit?.dataset.edit||change?.dataset.toggle,row=state.rows.find((item)=>String(item.institucion_id)===id);if(edit)openForm(row);if(change)toggle(row);});form.addEventListener('submit',save);window.previAdminShowInstitutions=show;
})();
