'use strict';

(() => {
  const sessionUser = window.previEduCurrentUser;
  if (!sessionUser || sessionUser.role !== 'DIRECTOR') return;
  const db = window.supabaseClient;
  const menu = document.querySelector('#main-menu');
  const main = document.querySelector('main .container-xl');
  const link = [...menu.querySelectorAll('.nav-link')].find((item) => item.textContent.trim() === 'Seguimientos');
  if (!db || !main || !link) return;

  main.insertAdjacentHTML('beforeend', `
    <section class="d-none followups-view" id="followups-view" aria-label="Seguimientos">
      <div class="students-tabs-wrapper"><div class="nav students-tabs" role="tablist"><button class="nav-link active" type="button" data-followups-tab="list">Seguimientos</button><button class="nav-link" type="button" data-followups-tab="upcoming">Próximas acciones</button><button class="nav-link" type="button" data-followups-tab="history">Historial por estudiante</button></div></div>
      <div class="alert d-none students-feedback" id="followups-feedback" role="status"></div>
      <div class="followups-pane" id="followups-pane-list">
        <div class="followups-kpis"><article><span class="students-heading-icon icon-violet">✓</span><div><small>Total de seguimientos</small><strong id="followups-total">—</strong></div></article><article><span class="students-heading-icon icon-sky">▣</span><div><small>Seguimientos este mes</small><strong id="followups-month">—</strong></div></article><article><span class="students-heading-icon icon-coral">!</span><div><small>Próximas acciones pendientes</small><strong id="followups-pending">—</strong></div></article><article><span class="students-heading-icon icon-green">◎</span><div><small>Estudiantes con seguimiento</small><strong id="followups-students">—</strong></div></article></div>
        <article class="card students-card"><div class="card-header students-card-header teachers-action-header"><div class="students-heading"><span class="students-heading-icon icon-violet">✓</span><div><h2 class="card-title">Seguimientos</h2><p>Consulte y registre las acciones preventivas realizadas con los estudiantes.</p></div></div><button class="btn btn-primary btn-sm" id="new-followup-record-button" type="button">+ Registrar seguimiento</button></div>
          <div class="card-body followups-filters" id="followups-filters">${filter('year','Año escolar')}${filter('level','Nivel')}${filter('grade','Grado',true)}${filter('classroom','Sección',true)}${filter('type','Tipo')}${filter('risk','Riesgo')}${filter('status','Estado de alerta')}<div><label>Desde</label><input data-filter="from" type="date"></div><div><label>Hasta</label><input data-filter="to" type="date"></div><div class="followups-search"><label>Estudiante</label><input data-filter="search" type="search" placeholder="Nombre o código"></div></div>
          <div class="students-loading" id="followups-loading"><span class="spinner-border spinner-border-sm"></span> Cargando seguimientos...</div><div class="table-responsive d-none" id="followups-table"><table class="table table-vcenter card-table followups-table"><thead><tr><th>Fecha</th><th>Estudiante</th><th>Grado / Sección</th><th>Riesgo</th><th>Tipo</th><th>Responsable</th><th>Próxima acción</th><th>Fecha próxima</th><th>Acciones</th></tr></thead><tbody id="followups-body"></tbody></table></div><p class="students-message d-none" id="followups-empty">No se encontraron seguimientos.</p><div class="alerts-pagination" id="followups-pagination"></div>
        </article>
      </div>
      <div class="followups-pane d-none" id="followups-pane-upcoming"><article class="card students-card"><div class="card-header students-card-header"><div class="students-heading"><span class="students-heading-icon icon-coral">▣</span><div><h2 class="card-title">Próximas acciones</h2><p>Compromisos pendientes ordenados por fecha</p></div></div></div><div class="card-body"><div class="upcoming-actions-grid" id="upcoming-actions-list"></div><p class="students-message d-none" id="upcoming-actions-empty">No hay próximas acciones registradas.</p></div></article></div>
      <div class="followups-pane d-none" id="followups-pane-history"><article class="card students-card"><div class="card-header students-card-header"><div class="students-heading"><span class="students-heading-icon icon-sky">◎</span><div><h2 class="card-title">Historial por estudiante</h2><p>Intervenciones preventivas y alerta relacionada</p></div></div></div><div class="card-body"><div class="history-selector"><label class="form-label">Buscar estudiante</label><select class="form-select" id="followups-history-student"><option value="">Seleccione un estudiante</option></select></div><div class="d-none" id="followups-history-content"><div class="profile-summary" id="followups-history-summary"></div><div class="followups-timeline" id="followups-history-timeline"></div></div><p class="students-message" id="followups-history-empty">Seleccione un estudiante para visualizar su historial.</p></div></article></div>
    </section>
    <div class="modal modal-blur fade" id="followup-record-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><form class="modal-content student-form" id="followup-record-form" novalidate><div class="modal-header"><div><h2 class="modal-title" id="followup-record-title">Registrar seguimiento</h2><p class="modal-subtitle">Intervención vinculada a una alerta activa</p></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Estudiante / alerta activa *</label><select class="form-select" name="alerta_id" required></select></div><div class="col-md-6"><label class="form-label">Tipo *</label><select class="form-select" name="tipo_seguimiento_id" required></select></div><div class="col-md-6"><label class="form-label">Fecha *</label><input class="form-control" name="fecha" type="date" required></div><div class="col-12"><label class="form-label">Descripción *</label><textarea class="form-control" name="descripcion" rows="3" required></textarea></div><div class="col-12"><label class="form-label">Acuerdo</label><textarea class="form-control" name="acuerdo" rows="2"></textarea></div><div class="col-md-8"><label class="form-label">Próxima acción</label><input class="form-control" name="proxima_accion"></div><div class="col-md-4"><label class="form-label">Fecha próxima acción</label><input class="form-control" name="fecha_proxima_accion" type="date"></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Guardar seguimiento</button></div></form></div></div>
    <div class="modal modal-blur fade" id="followup-detail-modal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content student-profile"><div class="modal-header"><div><h2 class="modal-title">Detalle del seguimiento</h2><p class="modal-subtitle">Información de la intervención preventiva</p></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body" id="followup-detail-content"></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cerrar</button></div></div></div></div>`);

  function filter(name, label, disabled = false) { return `<div><label>${label}</label><select data-filter="${name}"${disabled ? ' disabled' : ''}></select></div>`; }
  const $ = (selector) => document.querySelector(selector);
  const relation = (item) => Array.isArray(item) ? item[0] : item;
  const safe = (item, fallback = 'No registrado') => item === null || item === undefined || item === '' ? fallback : String(item);
  const esc = (item) => safe(item).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[c]);
  const norm = (item) => safe(item, '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
  const formatDate = (item) => item ? new Intl.DateTimeFormat('es-PE', { timeZone: 'UTC' }).format(new Date(`${String(item).slice(0,10)}T00:00:00Z`)) : 'No registrado';
  const getData = (response, context) => { if (response.error) throw new Error(context, { cause: response.error }); return response.data || []; };
  const state = { followups:[], alerts:[], years:[], levels:[], grades:[], sections:[], classrooms:[], risks:[], statuses:[], types:[], directorId:null, loaded:false, page:1, size:10, editing:null };
  const selectFollowups = 'seguimiento_id,alerta_id,usuario_id,tipo_seguimiento_id,fecha,descripcion,acuerdo,proxima_accion,fecha_proxima_accion,fecha_registro,tipo_seguimiento(tipo_seguimiento_id,codigo,nombre),usuario(usuario_id,nombres,apellidos,nombre_usuario),alerta(alerta_id,titulo,descripcion,fecha_generacion,fecha_actualizacion,estado_alerta_id,estado_alerta(estado_alerta_id,codigo,nombre),analisis_riesgo(analisis_riesgo_id,fecha_analisis,nivel_riesgo(nivel_riesgo_id,codigo,nombre),matricula(matricula_id,estudiante(estudiante_id,codigo,nombres,apellido_paterno,apellido_materno),aula(aula_id,anio_escolar_id,grado_id,seccion_id,anio_escolar(anio_escolar_id,anio),grado(grado_id,nivel_id,nombre,nivel_educativo(nivel_id,nombre)),seccion(seccion_id,nombre)))))';
  const selectAlerts = 'alerta_id,titulo,descripcion,fecha_generacion,fecha_actualizacion,estado_alerta_id,estado_alerta(estado_alerta_id,codigo,nombre),analisis_riesgo(analisis_riesgo_id,fecha_analisis,nivel_riesgo(nivel_riesgo_id,codigo,nombre),matricula(matricula_id,estudiante(estudiante_id,codigo,nombres,apellido_paterno,apellido_materno),aula(aula_id,anio_escolar_id,grado_id,seccion_id,anio_escolar(anio_escolar_id,anio),grado(grado_id,nivel_id,nombre,nivel_educativo(nivel_id,nombre)),seccion(seccion_id,nombre)))))';
  const parts = (item) => { const alert = relation(item.alerta) || item; const analysis = relation(alert.analisis_riesgo); const enrollment = relation(analysis?.matricula); const student = relation(enrollment?.estudiante); const classroom = relation(enrollment?.aula); const grade = relation(classroom?.grado); return { alert, analysis, enrollment, student, classroom, grade, section:relation(classroom?.seccion), level:relation(grade?.nivel_educativo), year:relation(classroom?.anio_escolar), risk:relation(analysis?.nivel_riesgo), alertState:relation(alert?.estado_alerta) }; };
  const fullName = (student) => [student?.nombres,student?.apellido_paterno,student?.apellido_materno].filter(Boolean).join(' ') || 'No registrado';
  const badge = (code, kind='risk') => `<span class="badge alert-${kind} ${kind === 'risk' ? 'risk' : 'state'}-${norm(code)}">${esc(code || 'No registrado')}</span>`;
  const today = () => new Intl.DateTimeFormat('en-CA', { timeZone:'America/Lima' }).format(new Date());

  async function load() {
    const responses = await Promise.all([
      db.from('seguimiento').select(selectFollowups).in('alerta_id',window.appContext.scope.alertIds).order('fecha', { ascending:false }), db.from('alerta').select(selectAlerts).in('alerta_id',window.appContext.scope.alertIds),
      db.from('anio_escolar').select('anio_escolar_id,anio,estado').eq('institucion_id',window.appContext.currentInstitution.institucion_id).order('anio',{ascending:false}), db.from('nivel_educativo').select('nivel_id,nombre,estado').order('nombre'), db.from('grado').select('grado_id,nivel_id,nombre,orden,estado').order('orden'), db.from('seccion').select('seccion_id,nombre,estado').order('nombre'), db.from('aula').select('aula_id,anio_escolar_id,grado_id,seccion_id,estado').in('anio_escolar_id',window.appContext.scope.yearIds), db.from('nivel_riesgo').select('nivel_riesgo_id,codigo,nombre,estado').order('orden'), db.from('estado_alerta').select('estado_alerta_id,codigo,nombre,estado').order('orden'), db.from('tipo_seguimiento').select('tipo_seguimiento_id,codigo,nombre,estado').eq('estado',true).order('nombre'), db.from('usuario').select('usuario_id').eq('nombre_usuario',sessionUser.username).eq('rol','DIRECTOR').maybeSingle()
    ]);
    [state.followups,state.alerts,state.years,state.levels,state.grades,state.sections,state.classrooms,state.risks,state.statuses,state.types] = responses.slice(0,10).map((r,i) => getData(r, `Consulta ${i + 1}`));
    const user = responses[10]; if (user.error) throw new Error('Usuario responsable', { cause:user.error }); state.directorId = user.data?.usuario_id || null;
  }
  function fill(select, rows, placeholder, key, label) { select.replaceChildren(new Option(placeholder,'')); rows.forEach((row) => select.add(new Option(label(row),row[key]))); select.disabled = false; }
  function initFilters() { const box=$('#followups-filters'); fill(box.querySelector('[data-filter="year"]'),state.years,'Todos','anio_escolar_id',(r)=>r.anio); fill(box.querySelector('[data-filter="level"]'),state.levels,'Todos','nivel_id',(r)=>r.nombre); fill(box.querySelector('[data-filter="type"]'),state.types,'Todos','tipo_seguimiento_id',(r)=>r.nombre); fill(box.querySelector('[data-filter="risk"]'),state.risks,'Todos','codigo',(r)=>r.nombre); fill(box.querySelector('[data-filter="status"]'),state.statuses,'Todos','codigo',(r)=>r.nombre); box.querySelectorAll('select,input').forEach((el)=>el.addEventListener(el.tagName==='INPUT'?'input':'change',()=>{state.page=1;renderList();})); box.querySelector('[data-filter="level"]').addEventListener('change',()=>{ const id=box.querySelector('[data-filter="level"]').value; fill(box.querySelector('[data-filter="grade"]'),state.grades.filter((g)=>!id||String(g.nivel_id)===id),'Todos','grado_id',(g)=>g.nombre); updateClassrooms(); }); box.querySelector('[data-filter="grade"]').addEventListener('change',updateClassrooms); box.querySelector('[data-filter="year"]').addEventListener('change',updateClassrooms); }
  function updateClassrooms(){ const box=$('#followups-filters'), year=box.querySelector('[data-filter="year"]').value, grade=box.querySelector('[data-filter="grade"]').value; const rows=state.classrooms.filter((a)=>(!year||String(a.anio_escolar_id)===year)&&(!grade||String(a.grado_id)===grade)); fill(box.querySelector('[data-filter="classroom"]'),rows,'Todas','aula_id',(a)=>state.sections.find((s)=>s.seccion_id===a.seccion_id)?.nombre||'Aula'); box.querySelector('[data-filter="classroom"]').disabled=!grade; }
  function filtered(){ const box=$('#followups-filters'), get=(n)=>box.querySelector(`[data-filter="${n}"]`).value; return state.followups.filter((item)=>{const p=parts(item), search=norm(get('search')); return (!get('year')||String(p.year?.anio_escolar_id)===get('year'))&&(!get('level')||String(p.level?.nivel_id)===get('level'))&&(!get('grade')||String(p.grade?.grado_id)===get('grade'))&&(!get('classroom')||String(p.classroom?.aula_id)===get('classroom'))&&(!get('type')||String(item.tipo_seguimiento_id)===get('type'))&&(!get('risk')||p.risk?.codigo===get('risk'))&&(!get('status')||p.alertState?.codigo===get('status'))&&(!get('from')||item.fecha>=get('from'))&&(!get('to')||item.fecha<=get('to'))&&(!search||norm(`${p.student?.codigo} ${fullName(p.student)}`).includes(search));}); }
  function renderKpis(){ const month=today().slice(0,7), pending=state.followups.filter((s)=>s.fecha_proxima_accion&&parts(s).alertState?.codigo!=='CERRADA'); $('#followups-total').textContent=state.followups.length; $('#followups-month').textContent=state.followups.filter((s)=>s.fecha?.startsWith(month)).length; $('#followups-pending').textContent=pending.length; $('#followups-students').textContent=new Set(state.followups.map((s)=>parts(s).student?.estudiante_id).filter(Boolean)).size; }
  function renderList(){ const rows=filtered(), start=(state.page-1)*state.size, body=$('#followups-body'); body.replaceChildren(); rows.slice(start,start+state.size).forEach((item)=>{const p=parts(item), type=relation(item.tipo_seguimiento), user=relation(item.usuario), tr=document.createElement('tr'); tr.innerHTML=`<td>${formatDate(item.fecha)}</td><td><strong>${esc(fullName(p.student))}</strong><small>${esc(p.student?.codigo)}</small></td><td>${esc(`${p.grade?.nombre||''} ${p.section?.nombre||''}`.trim())}</td><td>${badge(p.risk?.codigo)}</td><td>${esc(type?.nombre)}</td><td>${esc([user?.nombres,user?.apellidos].filter(Boolean).join(' '))}</td><td>${esc(item.proxima_accion)}</td><td>${formatDate(item.fecha_proxima_accion)}</td>`; const actions=document.createElement('td'); actions.className='followup-row-actions'; actions.append(button('Ver detalle',()=>openDetail(item)),button('Editar',()=>openForm(item))); tr.append(actions); body.append(tr);}); $('#followups-table').classList.toggle('d-none',!rows.length); $('#followups-empty').classList.toggle('d-none',rows.length>0); pagination(rows.length); }
  function button(label,fn){const b=document.createElement('button');b.type='button';b.className='btn btn-sm btn-outline-primary w-fit';b.textContent=label;b.addEventListener('click',fn);return b;}
  function pagination(total){const box=$('#followups-pagination');box.replaceChildren();if(!total)return;const pages=Math.max(1,Math.ceil(total/state.size));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.size;const label=document.createElement('span');label.textContent=`Mostrando ${start+1} a ${Math.min(start+state.size,total)} de ${total} seguimientos`;const controls=document.createElement('div'),size=document.createElement('select');size.className='form-select form-select-sm';[10,20,30].forEach(n=>size.add(new Option(n,n,false,n===state.size)));size.onchange=()=>{state.size=Number(size.value);state.page=1;renderList();};controls.append(size);[['«',1],['‹',state.page-1],['›',state.page+1],['»',pages]].forEach(([l,p])=>{const b=button(l,()=>{state.page=p;renderList();});b.className='btn btn-sm btn-outline-secondary';b.disabled=p<1||p>pages||p===state.page;controls.append(b);});box.append(label,controls);}
  function temporal(value){const day=String(value).slice(0,10), now=today();return day<now?'VENCIDA':day===now?'HOY':'PRÓXIMA';}
  function renderUpcoming(){const rows=state.followups.filter((s)=>s.fecha_proxima_accion&&parts(s).alertState?.codigo!=='CERRADA').sort((a,b)=>a.fecha_proxima_accion.localeCompare(b.fecha_proxima_accion)),box=$('#upcoming-actions-list');box.replaceChildren();rows.forEach((item)=>{const p=parts(item),user=relation(item.usuario),status=temporal(item.fecha_proxima_accion),card=document.createElement('article');card.className='upcoming-action-card';card.innerHTML=`<div><span class="badge due-${norm(status)}">${status}</span><time>${formatDate(item.fecha_proxima_accion)}</time></div><h3>${esc(fullName(p.student))}</h3><p>${esc(item.proxima_accion)}</p><dl><div><dt>Aula</dt><dd>${esc(`${p.grade?.nombre||''} ${p.section?.nombre||''}`.trim())}</dd></div><div><dt>Riesgo</dt><dd>${badge(p.risk?.codigo)}</dd></div><div><dt>Último seguimiento</dt><dd>${formatDate(item.fecha)}</dd></div><div><dt>Responsable</dt><dd>${esc([user?.nombres,user?.apellidos].filter(Boolean).join(' '))}</dd></div></dl>`;card.append(button('Ver detalle',()=>openDetail(item)));box.append(card);});$('#upcoming-actions-empty').classList.toggle('d-none',rows.length>0);}
  function renderHistoryOptions(){const map=new Map();state.alerts.forEach((a)=>{const p=parts(a);if(p.student)map.set(p.student.estudiante_id,p.student);});const select=$('#followups-history-student');select.replaceChildren(new Option('Seleccione un estudiante',''));[...map.values()].sort((a,b)=>fullName(a).localeCompare(fullName(b))).forEach((s)=>select.add(new Option(`${s.codigo} — ${fullName(s)}`,s.estudiante_id)));}
  function renderHistory(){const id=Number($('#followups-history-student').value),content=$('#followups-history-content'),empty=$('#followups-history-empty');if(!id){content.classList.add('d-none');empty.classList.remove('d-none');return;}const alerts=state.alerts.filter((a)=>parts(a).student?.estudiante_id===id), rows=state.followups.filter((s)=>parts(s).student?.estudiante_id===id).sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha))), current=[...alerts].sort((a,b)=>String(b.fecha_generacion).localeCompare(String(a.fecha_generacion)))[0],p=parts(current||rows[0]);$('#followups-history-summary').innerHTML=`<div><span>Estudiante</span><strong>${esc(fullName(p.student))}</strong></div><div><span>Código</span><strong>${esc(p.student?.codigo)}</strong></div><div><span>Aula</span><strong>${esc(`${p.grade?.nombre||''} ${p.section?.nombre||''}`.trim())}</strong></div><div><span>Riesgo actual</span>${badge(p.risk?.codigo)}</div><div><span>Estado de alerta</span>${badge(p.alertState?.codigo,'state')}</div>`;const timeline=$('#followups-history-timeline');timeline.replaceChildren();if(current){const context=document.createElement('article');context.className='history-alert-context';context.innerHTML=`<strong>${esc(current.titulo)}</strong><span>${badge(p.risk?.codigo)} ${badge(p.alertState?.codigo,'state')} · ${formatDate(current.fecha_generacion)}</span>`;const go=button('Ver detalle de alerta',()=>linkToAlerts());context.append(go);timeline.append(context);}if(!rows.length){const msg=document.createElement('span');msg.className='students-message1';msg.textContent='Aún no se han registrado seguimientos para esta alerta.';timeline.append(msg);const active=alerts.find((a)=>['NUEVA','SEGUIMIENTO'].includes(parts(a).alertState?.codigo));if(active)timeline.append(button('Registrar primer seguimiento',()=>openForm(null,active.alerta_id)));}rows.forEach((item)=>{const type=relation(item.tipo_seguimiento),user=relation(item.usuario),node=document.createElement('article');node.className='timeline-item';node.innerHTML=`<time>${formatDate(item.fecha)}</time><h3>${esc(type?.nombre)}</h3><small>${esc([user?.nombres,user?.apellidos].filter(Boolean).join(' '))}</small><p>${esc(item.descripcion)}</p><dl><div><dt>Acuerdo</dt><dd>${esc(item.acuerdo)}</dd></div><div><dt>Próxima acción</dt><dd>${esc(item.proxima_accion)}${item.fecha_proxima_accion?` · ${formatDate(item.fecha_proxima_accion)}`:''}</dd></div></dl>`;timeline.append(node);});content.classList.remove('d-none');empty.classList.add('d-none');}
  function linkToAlerts(){link.closest('#main-menu').querySelectorAll('.nav-link');const target=[...menu.querySelectorAll('.nav-link')].find((a)=>a.textContent.trim()==='Alertas');target?.click();}
  function activeAlerts(){return state.alerts.filter((a)=>['NUEVA','SEGUIMIENTO'].includes(parts(a).alertState?.codigo));}
  function openForm(item=null,alertId=null){state.editing=item;const form=$('#followup-record-form');form.reset();form.classList.remove('was-validated');fill(form.elements.alerta_id,activeAlerts(),'Seleccione estudiante / alerta','alerta_id',(a)=>{const p=parts(a);return `${p.student?.codigo} — ${fullName(p.student)} · ${a.titulo}`;});fill(form.elements.tipo_seguimiento_id,state.types,'Seleccione un tipo','tipo_seguimiento_id',(t)=>t.nombre);form.elements.alerta_id.disabled=Boolean(item);$('#followup-record-title').textContent=item?'Editar seguimiento':'Registrar seguimiento';if(item){form.elements.alerta_id.add(new Option('Alerta vinculada',item.alerta_id,true,true));form.elements.tipo_seguimiento_id.value=item.tipo_seguimiento_id;['fecha','descripcion','acuerdo','proxima_accion','fecha_proxima_accion'].forEach((n)=>form.elements[n].value=item[n]||'');}else{form.elements.fecha.value=today();if(alertId)form.elements.alerta_id.value=alertId;}new window.tabler.Modal($('#followup-record-modal')).show();}
  async function save(event){event.preventDefault();const form=event.currentTarget;if(!form.checkValidity()){form.classList.add('was-validated');return;}const fd=new FormData(form),payload={tipo_seguimiento_id:Number(fd.get('tipo_seguimiento_id')),fecha:fd.get('fecha'),descripcion:fd.get('descripcion').trim(),acuerdo:fd.get('acuerdo').trim()||null,proxima_accion:fd.get('proxima_accion').trim()||null,fecha_proxima_accion:fd.get('fecha_proxima_accion')||null},submit=form.querySelector('[type="submit"]');submit.disabled=true;submit.textContent=state.editing?'Actualizando información...':'Guardando seguimiento...';try{if(state.editing){getData(await db.from('seguimiento').update(payload).eq('seguimiento_id',state.editing.seguimiento_id),'No se pudo actualizar');}else{if(!state.directorId)throw new Error('No se pudo identificar el responsable');payload.alerta_id=Number(fd.get('alerta_id'));payload.usuario_id=state.directorId;payload.fecha_registro=new Date().toISOString();getData(await db.from('seguimiento').insert(payload),'No se pudo registrar');const alert=state.alerts.find((a)=>a.alerta_id===payload.alerta_id);if(parts(alert).alertState?.codigo==='NUEVA'){const status=state.statuses.find((s)=>s.codigo==='SEGUIMIENTO');getData(await db.from('alerta').update({estado_alerta_id:status.estado_alerta_id,fecha_actualizacion:new Date().toISOString()}).eq('alerta_id',payload.alerta_id),'No se pudo actualizar la alerta');}}window.tabler.Modal.getInstance($('#followup-record-modal'))?.hide();feedback(state.editing?'Seguimiento actualizado correctamente.':'Seguimiento registrado correctamente.');await refresh();}catch(error){console.error('[Seguimientos] Error al guardar',error.cause||error);feedback('No se pudo guardar la información.',false);}finally{submit.disabled=false;submit.textContent='Guardar seguimiento';}}
  function openDetail(item){const p=parts(item),type=relation(item.tipo_seguimiento),user=relation(item.usuario);$('#followup-detail-content').innerHTML=`<div class="profile-summary"><div><span>Estudiante</span><strong>${esc(fullName(p.student))}</strong></div><div><span>Código</span><strong>${esc(p.student?.codigo)}</strong></div><div><span>Año escolar</span><strong>${esc(p.year?.anio)}</strong></div><div><span>Nivel</span><strong>${esc(p.level?.nombre)}</strong></div><div><span>Grado / Sección</span><strong>${esc(`${p.grade?.nombre||''} ${p.section?.nombre||''}`.trim())}</strong></div><div><span>Riesgo</span>${badge(p.risk?.codigo)}</div><div><span>Estado de alerta</span>${badge(p.alertState?.codigo,'state')}</div></div><section class="profile-card"><h3>Datos del seguimiento</h3><dl class="followup-detail-grid"><div><dt>Tipo</dt><dd>${esc(type?.nombre)}</dd></div><div><dt>Fecha</dt><dd>${formatDate(item.fecha)}</dd></div><div><dt>Responsable</dt><dd>${esc([user?.nombres,user?.apellidos].filter(Boolean).join(' '))}</dd></div><div><dt>Fecha de registro</dt><dd>${formatDate(item.fecha_registro)}</dd></div><div><dt>Descripción</dt><dd>${esc(item.descripcion)}</dd></div><div><dt>Acuerdo</dt><dd>${esc(item.acuerdo)}</dd></div><div><dt>Próxima acción</dt><dd>${esc(item.proxima_accion)}</dd></div><div><dt>Fecha próxima acción</dt><dd>${formatDate(item.fecha_proxima_accion)}</dd></div></dl></section>`;new window.tabler.Modal($('#followup-detail-modal')).show();}
  function feedback(message,ok=true){const el=$('#followups-feedback');el.textContent=message;el.className=`alert students-feedback ${ok?'alert-success':'alert-danger'}`;}
  function activate(name){document.querySelectorAll('[data-followups-tab]').forEach((b)=>{const active=b.dataset.followupsTab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));});document.querySelectorAll('.followups-pane').forEach((p)=>p.classList.toggle('d-none',p.id!==`followups-pane-${name}`));if(name==='upcoming')renderUpcoming();if(name==='history')renderHistory();}
  function show(event){event.preventDefault();['#dashboard-director','#institution-view','#academic-management-view','#students-view','#teachers-view','#alerts-view'].forEach((s)=>$(s)?.classList.add('d-none'));$('#followups-view').classList.remove('d-none');$('#dashboard-title').textContent='SEGUIMIENTOS';$('#dashboard-subtitle').textContent='Historial de intervención preventiva';menu.querySelectorAll('.nav-link').forEach((a)=>a.classList.toggle('active',a===link));activate('list');if(!state.loaded)initialize();}
  async function refresh(){await load();renderKpis();renderList();renderUpcoming();renderHistoryOptions();renderHistory();}
  async function initialize(){try{await load();initFilters();renderKpis();renderList();renderUpcoming();renderHistoryOptions();state.loaded=true;}catch(error){console.error('[Seguimientos] Error al iniciar',error.cause||error);feedback('No se pudo cargar la información.',false);}finally{$('#followups-loading').classList.add('d-none');}}
  link.addEventListener('click',show);[...menu.querySelectorAll('.nav-link')].filter((a)=>a!==link).forEach((a)=>a.addEventListener('click',()=>$('#followups-view').classList.add('d-none')));document.querySelectorAll('[data-followups-tab]').forEach((b)=>b.addEventListener('click',()=>activate(b.dataset.followupsTab)));$('#new-followup-record-button').addEventListener('click',()=>openForm());$('#followup-record-form').addEventListener('submit',save);$('#followups-history-student').addEventListener('change',renderHistory);
})();
